// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTiHy8WnG62Isodt9Atk2eM_sHNCCpPI',
    appId: '1:52334712634:web:ece1590e0a6ae7b2f76203',
    messagingSenderId: '52334712634',
    projectId: 'flutter-modcom',
    authDomain: 'flutter-modcom.firebaseapp.com',
    storageBucket: 'flutter-modcom.appspot.com',
    measurementId: 'G-GYMEPCBB3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgIUozbQ_z79WaK1gfVr1Rm3HWsCe8nZE',
    appId: '1:52334712634:android:32a84a939d2090a0f76203',
    messagingSenderId: '52334712634',
    projectId: 'flutter-modcom',
    storageBucket: 'flutter-modcom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhMEYvtOOewqgWr5MECRw21GcKJeoqbc',
    appId: '1:52334712634:ios:4900b2a0e8e8e216f76203',
    messagingSenderId: '52334712634',
    projectId: 'flutter-modcom',
    storageBucket: 'flutter-modcom.appspot.com',
    iosClientId: '52334712634-udqvqip1lm35l2k1g8080cmbf3sqlg8s.apps.googleusercontent.com',
    iosBundleId: 'ke.co.titus.modcom.messages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBhMEYvtOOewqgWr5MECRw21GcKJeoqbc',
    appId: '1:52334712634:ios:4900b2a0e8e8e216f76203',
    messagingSenderId: '52334712634',
    projectId: 'flutter-modcom',
    storageBucket: 'flutter-modcom.appspot.com',
    iosClientId: '52334712634-udqvqip1lm35l2k1g8080cmbf3sqlg8s.apps.googleusercontent.com',
    iosBundleId: 'ke.co.titus.modcom.messages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjTiHy8WnG62Isodt9Atk2eM_sHNCCpPI',
    appId: '1:52334712634:web:42f7e2de8da66c2ff76203',
    messagingSenderId: '52334712634',
    projectId: 'flutter-modcom',
    authDomain: 'flutter-modcom.firebaseapp.com',
    storageBucket: 'flutter-modcom.appspot.com',
    measurementId: 'G-8VP4G84Q8H',
  );
}
