// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6_ncOTJIZlS5s4etGLbZdh_5M0c0ci8w',
    appId: '1:322594516981:web:e3cd25578386389d05babc',
    messagingSenderId: '322594516981',
    projectId: 'flutter-david',
    authDomain: 'flutter-david.firebaseapp.com',
    storageBucket: 'flutter-david.appspot.com',
    measurementId: 'G-S1GT29K3F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ovlFnPXqk4_76NG12v_kzpHFnQgiaio',
    appId: '1:322594516981:android:86d889a101914f3205babc',
    messagingSenderId: '322594516981',
    projectId: 'flutter-david',
    storageBucket: 'flutter-david.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidyNyquVeaXLrOz32fV4kQ10F0anDQTk',
    appId: '1:322594516981:ios:a8e63f767523b10305babc',
    messagingSenderId: '322594516981',
    projectId: 'flutter-david',
    storageBucket: 'flutter-david.appspot.com',
    iosBundleId: 'ke.co.modcom.flutter.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBidyNyquVeaXLrOz32fV4kQ10F0anDQTk',
    appId: '1:322594516981:ios:a8e63f767523b10305babc',
    messagingSenderId: '322594516981',
    projectId: 'flutter-david',
    storageBucket: 'flutter-david.appspot.com',
    iosBundleId: 'ke.co.modcom.flutter.lms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6_ncOTJIZlS5s4etGLbZdh_5M0c0ci8w',
    appId: '1:322594516981:web:a09b48ed0a25473105babc',
    messagingSenderId: '322594516981',
    projectId: 'flutter-david',
    authDomain: 'flutter-david.firebaseapp.com',
    storageBucket: 'flutter-david.appspot.com',
    measurementId: 'G-ZP7QELHSLX',
  );
}
